#!/bin/bash
###############################################################################
# ── User config ──────────────────────────────────────────────────────────────
# Input lyrics file (one line per lyric phrase; blank lines separate sections)
ORIGINAL_LYRIC_PATH="./example_input/lyrics_25.txt"
OUTPUT_DIR="./output_composerflow/25/"

# SoulX-Singer voice prompt (reference speaker for vocal synthesis)
SINGER_GENDER="female" # use male or female, the pitch picking has to know the gender to select the region
SOULX_PROMPT_WAV="./example_input/zh_prompt.mp3" # The voice prompt should be less then 10 seconds
PROMPT_LANGUAGE="Mandarin" # The voice prompt can be either Mandarin, English or Cantonese
VOCAL_SEP=False # if the vocal prompt contains backing track; set True if the wav has backing music
# Mode selector: "47s" | "full_song"
#   47s       → MuseControlLite_inference_47s_scale_up.py, one text prompt per run
#   full_song → MuseControlLite_inference_continuation.py, uses structure tag prompts
MODE="full_song"
MUSECONTROLLITE_CHECKPOINT="./MIDI-SAG_checkpoints/MuseControlLite_checkpoint"
# Chord style for harmonization: POP_STANDARD | POP_COMPLEX | DARK | RANDB | NOCONSTRAINT
CHORD_STYLE="POP_STANDARD"
CHORDS_PER_BAR=1
# Musical key of the vocal melody passed to AccoMontage2/demo_SOME.py.
#   Major: C  C#  Db  D  D#  Eb  E  F  F#  Gb  G  G#  Ab  A  A#  Bb  B
#   Minor: Cm C#m Dbm Dm D#m Ebm Em Fm F#m Gbm Gm G#m Abm Am A#m Bbm Bm
#   auto : read MIDI key_signature, fall back to Bellman-Budge heuristic
KEY="auto"
# Default text prompt for backing track generation (used as fallback in full_song
# mode when a structure tag has no entry in STRUCTURE_TAG_PROMPTS).
BACKING_TEXT_PROMPT="piano and drums, in the style of pop music"

# ── 47s mode config ──────────────────────────────────────────────────────────
# Wraps the single BACKING_TEXT_PROMPT into an array; add more entries if desired.
BACKING_TEXT_PROMPTS=( "$BACKING_TEXT_PROMPT" )

# ── Full-song (continuation) mode config ─────────────────────────────────────
# Default text prompt per structure tag (edit to taste).
# Tags not listed here fall back to BACKING_TEXT_PROMPT above.
# Valid tags: intro, verse, chorus, bridge, outro, break, inst, solo

declare -A STRUCTURE_TAG_PROMPTS=(
    [intro]="Clean electric guitar arpeggios with reverb."
    [verse]="Female vocal with guitars and light drums."
    [chorus]="Full band with soaring guitar harmonies and stronger rhythm."
    [bridge]="Reflective instrumental passage with piano, synth pad, bass, and gentle percussion"
    [outro]="Guitars sustain while drums slowly fade."
    [break]="Minimal instrumental break with sparse percussion and ambient textures"
    [inst]="Instrumental section with expressive lead melody and full band accompaniment"
    [solo]="Virtuosic instrumental solo with dynamic expression and energy"
)
# Note: In ComposeFlow, structure times and tags are auto-generated by the
# lyrics→melody pipeline (step 1), so there is no need to set them manually.
###############################################################################
# you do not need to modify the following
# ── Resolve relative user paths to absolute (before any cd) ──────────────────
ORIGINAL_LYRIC_PATH="$(readlink -f "$ORIGINAL_LYRIC_PATH")"
SOULX_PROMPT_WAV="$(readlink -f "$SOULX_PROMPT_WAV")"
mkdir -p "$OUTPUT_DIR"
OUTPUT_DIR="$(cd "$OUTPUT_DIR" && pwd)"

# ── Derived paths ─────────────────────────────────────────────────────────────
LYRIC_PATH="$OUTPUT_DIR/sample01.txt"
SOULX_SAVE_DIR="$OUTPUT_DIR/vocal_audio"
MIDI_DIR="$OUTPUT_DIR/lyrics2melody"
BPM_PATH="$MIDI_DIR/sample01.json"
TIME_LYRIC_PATH="$MIDI_DIR/sample01_times.txt"
STRUCT_label_LIST="$MIDI_DIR/sample01_struct_label.json"
STRUCT_time_LIST="$MIDI_DIR/sample01_struct_time.json"
GENERATED_MIDI="$MIDI_DIR/sample01.mid"
TARGET_META="$MIDI_DIR/sample01_soulx.json"
CHORD_DIR="$MIDI_DIR/chord/$CHORD_STYLE"
SOULX_PROMPT_TRANSCRIPTION_DIR="$OUTPUT_DIR/prompt_transcription"
SONG_NAME="sample01"
HARMONIZE_DIR="$OUTPUT_DIR/Harmonization_results"
CHORD_PATH="$HARMONIZE_DIR/btc_txt/${SONG_NAME}_chord_gen.txt"
PROMPT_LOG_PATH="$OUTPUT_DIR/Mixed_track/prompts_used.txt"

# ── 1. CSL-L2M: Lyrics → MIDI ───────────────────────────────────────────────
mkdir -p "$MIDI_DIR"
cd /data/home/fundwotsai/MIDI-SAG/lyrics2melody_new
python -u generate.py \
    config/CSLL2M.yaml ../MIDI-SAG_checkpoints/pretrained_CSLL2M.pt \
    "$MIDI_DIR" 1 "$ORIGINAL_LYRIC_PATH"
python -u read_midi.py $GENERATED_MIDI $LYRIC_PATH
python -u pitch_picking.py $GENERATED_MIDI --bpm $BPM_PATH --singer $SINGER_GENDER
python -u read_midi_lyrics_timestamp.py $MIDI_DIR
python -u match_segment_times.py $ORIGINAL_LYRIC_PATH $TIME_LYRIC_PATH $STRUCT_time_LIST $STRUCT_label_LIST

# ── 2. Convert generated MIDI → SoulX-Singer JSON ───────────────────────────
cd /data/home/fundwotsai/MIDI-SAG/SoulX-Singer
python midi2json.py "$GENERATED_MIDI" "$TARGET_META" --language "Mandarin"

# ── 2.5. Preprocess vocal prompt WAV → metadata JSON ────────────────────────
mkdir -p "$SOULX_PROMPT_TRANSCRIPTION_DIR"
python -m preprocess.pipeline \
    --audio_path "$SOULX_PROMPT_WAV" \
    --save_dir "$SOULX_PROMPT_TRANSCRIPTION_DIR" \
    --language "$PROMPT_LANGUAGE" \
    --device cuda \
    --vocal_sep $VOCAL_SEP \
    --max_merge_duration 90000
SOULX_PROMPT_META="$SOULX_PROMPT_TRANSCRIPTION_DIR/metadata.json"

# ── 3. SoulX-Singer: MIDI + JSON → Vocal audio ──────────────────────────────
python -m cli.inference \
    --device cuda \
    --model_path ../MIDI-SAG_checkpoints/SoulX-Singer/model.pt \
    --config soulxsinger/config/soulxsinger.yaml \
    --prompt_wav_path "$SOULX_PROMPT_WAV" \
    --prompt_metadata_path "$SOULX_PROMPT_META" \
    --target_metadata_path "$TARGET_META" \
    --phoneset_path soulxsinger/utils/phoneme/phone_set.json \
    --save_dir "$SOULX_SAVE_DIR" \
    --control score \
    # --auto_shift

# ── 4. AccoMontage2: MIDI → Chord harmonization ─────────────────────────────
cd /data/home/fundwotsai/MIDI-SAG

python AccoMontage2/demo_SOME.py \
    --midi_path "$GENERATED_MIDI" \
    --output_dir "$HARMONIZE_DIR" \
    --beat_subdivision 1 \
    --chord_style "$CHORD_STYLE" \
    --chords_per_bar "$CHORDS_PER_BAR" \
    --key "$KEY"

# ── 5. MuseControlLite: Backing track generation ────────────────────────────
# Locate the vocal audio generated by SoulX-Singer
VOCAL_AUDIO_PATH="$(find "$SOULX_SAVE_DIR" -maxdepth 1 -name '*.wav' | head -1)"
if [ -z "$VOCAL_AUDIO_PATH" ]; then
    echo "Error: no .wav found in $SOULX_SAVE_DIR" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR/Mixed_track"

case "$MODE" in
  47s)
    INFERENCE_SCRIPT="MuseControlLite/MuseControlLite_inference_47s_scale_up.py"
    echo "Mode: 47s — loading model once, generating ${#BACKING_TEXT_PROMPTS[@]} prompt(s)"

    if python "$INFERENCE_SCRIPT" \
        --vocal_audio_file "$VOCAL_AUDIO_PATH" \
        --text_prompt "${BACKING_TEXT_PROMPTS[@]}" \
        --chord_file "$CHORD_PATH" \
        --vocal_midi_file "$GENERATED_MIDI" \
        --checkpoint_path "$MUSECONTROLLITE_CHECKPOINT" \
        --output_dir "$OUTPUT_DIR/Mixed_track/"; then
        {
            printf 'inference_script=%s\n\n[text_prompts]\n' "$INFERENCE_SCRIPT"
            for i in "${!BACKING_TEXT_PROMPTS[@]}"; do
                printf '%d\t%s\n' "$((i + 1))" "${BACKING_TEXT_PROMPTS[$i]}"
            done
        } > "$PROMPT_LOG_PATH"
        echo "Saved prompts to $PROMPT_LOG_PATH"
    fi
    ;;

  full_song)
    INFERENCE_SCRIPT="MuseControlLite/MuseControlLite_inference_continuation.py"

    # Read structure from pipeline JSON outputs (step 1)
    readarray -t STRUCTURE_STARTS < <(python3 -c "import json; [print(x) for x in json.load(open('$STRUCT_time_LIST'))]")
    readarray -t STRUCTURE_TAGS   < <(python3 -c "import json; [print(x) for x in json.load(open('$STRUCT_label_LIST'))]")

    if [ ${#STRUCTURE_STARTS[@]} -eq 0 ]; then
        echo "Error: $STRUCT_time_LIST is empty or missing." >&2
        exit 1
    fi

    # Map each tag to its text prompt (fall back to BACKING_TEXT_PROMPT)
    STRUCTURE_PROMPTS=()
    for _tag in "${STRUCTURE_TAGS[@]}"; do
        if [ -n "${STRUCTURE_TAG_PROMPTS[$_tag]+x}" ]; then
            STRUCTURE_PROMPTS+=( "${STRUCTURE_TAG_PROMPTS[$_tag]}" )
        else
            echo "[WARN] No prompt for tag '$_tag'; using BACKING_TEXT_PROMPT" >&2
            STRUCTURE_PROMPTS+=( "$BACKING_TEXT_PROMPT" )
        fi
    done

    echo "Mode: full_song — continuation with ${#STRUCTURE_STARTS[@]} segment(s)"

    STRUCT_ARGS=(
        --structure_starts  "${STRUCTURE_STARTS[@]}"
        --structure_tags    "${STRUCTURE_TAGS[@]}"
        --structure_prompts "${STRUCTURE_PROMPTS[@]}"
    )

    if python "$INFERENCE_SCRIPT" \
        --vocal_audio_file "$VOCAL_AUDIO_PATH" \
        --chord_file "$CHORD_PATH" \
        --vocal_midi_file "$GENERATED_MIDI" \
        --checkpoint_path "$MUSECONTROLLITE_CHECKPOINT" \
        --output_dir "$OUTPUT_DIR/Mixed_track/" \
        "${STRUCT_ARGS[@]}"; then
        {
            printf 'inference_script=%s\n\n[structure_segments]\n' "$INFERENCE_SCRIPT"
            for i in "${!STRUCTURE_STARTS[@]}"; do
                printf '%d\t%s\t%s\t%s\n' \
                    "$((i + 1))" \
                    "${STRUCTURE_STARTS[$i]}" \
                    "${STRUCTURE_TAGS[$i]}" \
                    "${STRUCTURE_PROMPTS[$i]}"
            done
        } > "$PROMPT_LOG_PATH"
        echo "Saved prompts to $PROMPT_LOG_PATH"
    fi
    ;;

  *)
    echo "Error: MODE must be '47s' or 'full_song' (got '$MODE')." >&2
    exit 1
    ;;
esac
